apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      role: web
      instance: web1
  template:
    metadata:
      labels:
        app: nginx
        role: web
        instance: web1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: instance
                      operator: In
                      values:
                        - web1
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nginx
          image: gcr.io/socialmapp-f1941/nginx-pod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
